### ISSUE TITLE
Start with Windows key enabled

### ISSUE THREAD

**Issue by B00ze64** [clangen/winkill#1]
Good day.

Nice tool. Could we please have a command-line option to start WinKill with the Windows key enabled? I want to disable the key when I play games, but I use the computer for other things more than for playing games, so I want to click the icon when I play, but have the Windows Key enabled when I boot-up the computer.

Thank you.
Best Regards,

**Comment by clangen** [comment]
Good suggestion. I just uploaded version `0.3` that has a `/startDisabled` flag.

If `/startDisabled` is specified, the logic that suppresses the key presses will be disabled, and the Windows key will function as usual. If `/startDisabled` is **NOT** specified, the Windows key will be disabled on startup.

https://github.com/clangen/winkill/releases/tag/0.3

**Comment by B00ze64** [comment]
Wow, that was quick! Thanks! I will go try it out right now.

I had looked at the code, and was about to install VS Community, just so I could remove the 1 line where you called the hook upon creation of the SysTray icon. I first thought I would do the argc/argv thing myself but there's no way, your "main" was totally empty and I could not really follow how WinKill worked, I haven't programmed C in like 20 years.

Thanks again!

**Comment by B00ze64** [comment]
Works fine! Woohoo!
